### ISSUE TITLE
fhir-qb/mongo: `foo:missing=true` results in `foo: { $exists: true }` instead of `$exists: false`

### ISSUE THREAD

**Issue by navndn** [Asymmetrik/phx-tools#19]
As mentioned in the title, `qb.buildSearchQuery(req, configs)` is giving incorrect query for `:missing` modifier. Test-cases too have incorrect expectations. 
https://github.com/Asymmetrik/phx-tools/blob/master/packages/fhir-qb/index.test.js#L2505

Seems like a silly bug?

Version: 
    "@asymmetrik/fhir-qb": "^0.10.2"

**Comment by sshah-asymmetrik** [comment]
@navndn Good catch! I've created a bugfix branch to remedy this. We'll merge this in on our next publishing cycle.
