### ISSUE TITLE
Update README.md with "Getting setup"

### ISSUE THREAD

**Issue by joepaquette** [Asymmetrik/phx-tools#23]
Recommend copying the "Getting setup" section from the CONTRIBUTING.md into the README.md. 

I started out with `npm install` followed by `npm run bootstrap` resulting in various issues. Knowing the contents of the "Getting setup" section from the CONTRIBUTING.md upfront would have been very helpful.

**Comment by Robert-W** [comment]
@joepaquette What kinds of issues were you hitting. Theoretically those are the only commands you should need to run. I would like this to work with both yarn and npm, but if it only works with yarn package manager then i may need to check the lerna configurations.

We do have a link on the main page to the contributors guide that guides people interested in contributing to that section. We chose to put it there as we did not want to confuse users that were not interested in contributing and only interested in using the various packages. I'm a little hesitant to put it in the README and the CONTRIBUTING guide as then we have two sets of documentation that need to be kept in sync. Is there any way you can think we can make the link more obvious or make the setup less confusing?

**Comment by luan-dev** [comment]
Closing stale issue
