### ISSUE TITLE
Add TypeScript types to DefinitelyTyped

### ISSUE THREAD

**Issue by joepaquette** [Asymmetrik/phx-tools#24]
For Typescript developers, it would be very helpful if you contribute the type definitions for each of the packages to DefinitelyTyped (https://definitelytyped.org).

**Comment by Robert-W** [comment]
Hey @joepaquette, similar to my comment in the other repo. I'll bring this up with the team and update both tickets once we discuss timeline's and those kinds of things.

**Comment by luan-dev** [comment]
DefinitelyTyped added support for r4: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/fhir
