### ISSUE TITLE
Add resource generator to this package

### ISSUE THREAD

**Issue by joepaquette** [Asymmetrik/phx-tools#25]
Please consider adding your resource generator (ref: https://github.com/Asymmetrik/fhir-facade-starter/issues/9#issuecomment-439060675) to this repository as an additional package.

It would be helpful when we create/use custom profiles (custom StructureDefinitions) to be able to add them to our fhir server implementation.

**Comment by Robert-W** [comment]
@joepaquette  So this has been a bit of an internal debate for us as well. Currently, the resource generator is not planned to go open source, but we are planning to build a web service people can use to upload structure definitions and then download a package that can be plugged into various repos. We would still need to add some configurations to the open source repos to support this but it is high up on the roadmap. We were also planning on generating a package that could serve both Rest and GraphQL for the same version on the same server instance (read and write operations on Rest and read operations on GraphQL). 

I'll try to make sure I keep this issue updated with progress and links to the service as that happens. We have a prototype now but are working out content and design items at the moment. We also have an [early access program](https://asymmetrik.com/solutions/healthcare/code-generation/?referrer=healthcare) available for people interested in helping us test this out.
